export const INITIAL_DATA = {
  // basic details
  propertyType: '',
  propertyAge: '',
  rooms: '',
  bathrooms: '',
  balcony: '',
  furnishedType: '',
  coveredParking: '',
  openParking: '',
  availableForm: '',
  monthlyRent: '',
  maintenanceCharge: '',
  securityDeposit: '',
  area: '',
  carpetArea: '',
  preferedTenantType: [],
  // locationform
  city: '',
  buildingProjectSociety: '',
  locality: '',
  flatNumber: '',
  floorNumber: '',
  totalFloors: '',
  // photos
  photos: [],
  // propertyform
  lockInPeriod: '',
  facing: '',
  address: '',
  servantRoom: '',
  propertyDescription: '',
  // amenities
  amenities: [],
  societyAmenities: [],
};

export const LISTING_PROPERTY_ENUM = {
  apartment: 'apartment',
  villa: 'villa',
  independent_house: 'independent_house',
  independent_floor: 'independent_floor',
  fully_furnished: 'furnished',
  semi_furnished: 'semi furnished',
  unfurnished: 'unfurnished',
  yes_securityDeposit: 'yes',
  no_securityDeposit: 'no',
  onerk: '1 RK',
  onebhk: '1 BHK',
  twobhk: '2 BHK',
  threebhk: '3 BHK',
  fourbhk: '4 BHK',
  fivebhk: '5 BHK',
  sixbhk: '6 BHK',
  sevenbhk: '7 BHK',
  eightbhk: '8 BHK',
  ninebhk: '9 BHK',
  tenbhk: '10 BHK',
  zero_bathroom: '0',
  one_bathroom: '1',
  two_bathroom: '2',
  three_bathroom: '3',
  four_bathroom: '4',
  five_bathroom: '5',
  six_bathroom: '6',
  seven_bathroom: '7',
  eight_bathroom: '8',
  nine_bathroom: '9',
  zero_balcony: '0',
  one_balcony: '1',
  two_balcony: '2',
  three_balcony: '3',
  four_balcony: '4',
  five_balcony: '5',
  six_balcony: '6',
  seven_balcony: '7',
  eight_balcony: '8',
  nine_balcony: '9',
  zero_covered_parking: '0',
  one_covered_parking: '1',
  two_covered_parking: '2',
  three_covered_parking: '3',
  four_covered_parking: '4',
  five_covered_parking: '5',
  six_covered_parking: '6',
  seven_covered_parking: '7',
  eight_covered_parking: '8',
  nine_covered_parking: '9',
  zero_open_parking: '0',
  one_open_parking: '1',
  two_open_parking: '2',
  three_open_parking: '3',
  four_open_parking: '4',
  five_open_parking: '5',
  six_open_parking: '6',
  seven_open_parking: '7',
  eight_open_parking: '8',
  nine_open_parking: '9',
};

export const AMENITIES_ICON = {
  'Dining Table': 'dining-table',
  'Washing Machine': 'washing-machine',
  Sofa: 'sofa',
  Microwave: 'microwave',
  Stove: 'gas-stove',
  Fridge: 'fridge',
  'Water Purifier': 'faucet',
  'Gas Pipeline': 'gas-pipeline',
  AC: 'air-conditioner',
  Bed: 'bed',
  Tv: 'tv',
  Cupboard: 'cabinet',
  Geyser: 'water-boiler',
  Lift: 'elevator',
  CCTV: 'cctv',
  Gym: 'weight',
  Garden: 'garden',
  'Kids Area': 'seesaw',
  Sports: 'cricket',
  'Swimming Pool': 'swimming',
  Intercom: 'intercom',
  'Gated Area': 'gate',
  'Club House': 'house',
  'Community Hall': 'city-hall',
  'Regular Water': 'faucet',
  'Power Backup': 'lightbulb',
  'Pet Allowed': 'pet',
};
